version: '3'
networks: 
    ballot-network:
        driver: bridge
services: 
    frontend: 
        build: frontend
        restart: always
        ports: 
            - '5000:8080'
        depends_on: 
            - backend
        networks:
            - ballot-network
        environment: 
            - VUE_APP_URL=${API_URL}
    backend: 
        build: backend
        restart: always
        ports: 
            - '5010:4010'
        depends_on: 
            - db
        networks: 
            - ballot-network
        environment: 
            - NODE_ENV=production
    db:
        image: mysql:5.6
        environment: 
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports: 
            - '5020:3306'
        volumes: 
            - "db:/var/lib/mysql:rw"
        networks: 
            - ballot-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment: 
            PMA_HOST: db
            PMA_ABSOLUTE_URI: "${PMA_URL}"
        depends_on: 
            - db
        ports:
            - '5030:80'
        networks: 
            - ballot-network

volumes:
    db: