version: '3'
networks: 
    ballot-network:
        driver: bridge
services: 
    frontend: 
        build: frontend
        restart: always
        ports: 
            - '4000:8080'
        depends_on: 
            - backend
        networks:
            - ballot-network
    backend: 
        build: backend
        restart: always
        ports: 
            - '4010:4010'
        depends_on: 
            - db
        networks: 
            - ballot-network
    db:
        image: mysql:5.6
        environment: 
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports: 
            - '4020:3306'
        networks: 
            - ballot-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment: 
            PMA_HOST: db
        depends_on: 
            - db
        ports:
            - '4030:80'
        networks: 
            - ballot-network

